"""Create shows

Revision ID: 92f3006c6b1a
Revises: 06e2de3aee16
Create Date: 2021-10-30 19:57:24.871339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f3006c6b1a'
down_revision = '06e2de3aee16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starting_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artists', sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('venues', sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created_datetime')
    op.drop_column('artists', 'created_datetime')
    op.drop_table('shows')
    # ### end Alembic commands ###
